leave:
  apply:
    server:
      port: 7003
    config:
      eureka: http://discovery-service:8761/eureka
      
spring:
   jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
      
   datasource:
    url: jdbc:mysql://bslmsdemomysql.centralus.cloudapp.azure.com:3306/attendancedb?verifyServerCertificate=false&useSSL=false&autoReconnect=true
    username: msdemoadmin
    password: Sys@12345    
    hikari:
      connection-timeout: 35000
      minimum-idle: 1
      maximum-pool-size: 4
      idle-timeout: 10000
      max-lifetime: 1200000
      auto-commit: true
