leave:
  apply:
    server:
      port: 7003
    config:
      eureka: http://localhost:8761/eureka
      
spring:
   jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
      
   datasource:
    url: jdbc:mysql://localhost:3306/attendancedb?autoReconnect=true&useSSL=false
    username: msdemoadmin
    password: sys12345
